// Generated by https://quicktype.io

export interface EditOwnerData {
  ownerId: string;
  ownerMobileNo: number;
  alternateMobileNo?: string;
  emailId: string;
  ownerGender?: string;
  affiliatedAgencyUnionOrPc: boolean;
  villageInstitutionType: null;
  villageInstitutionCode: string;
  membershipNumber: null;
  ownerAddress: string;
  ownerAddressCityVillageCd: number;
  ownerAddressTehsilCd: number;
  ownerAddressDistrictCd: number;
  ownerAddressStateCd: number;
  ownerAddressPincode: null;
  ownerLandHoldingCd: number;
  isOwnerBelowPovertyLine: boolean;
  hhid: string;
  ownerCastCategoryCd: number;
  isCategoryVerified?: null;
  isPourerMember: boolean;
  ownerTypeCategoryCd?: string;
}
