// Generated by https://quicktype.io

export interface NewCaseResponse {
  data: any;
  caseId: number;
  followUpDate: string;
  sampleDetails: SampleDetail[];
}

export interface SampleDetail {
  sampleId: string;
  sampleType: number;
  sampleTypeDesc: string;
  testingLocation: number;
  testingLocationDesc: string;
  labCd?: number;
  labCdDesc?: string;
}
