// Generated by https://quicktype.io

import { CompleteOwnerDetails } from '../../owner-registration/models-owner-reg/get-ownerby-ownerID.model';

export interface LatestTags {
  latestTag: number;
  ownerDetails: CompleteOwnerDetails;
}
