export interface TehsilList {
  districtCode?: string;
  tehsilCode: number;
  tehsilName: string;
  tehsilCd?:number
  pinCd?:number;
}

// Generated by https://quicktype.io

export interface FLWVillages {
  districtCd: number;
  stateCd: number;
  tehsilCd: number;
  villageCd: number;
  stateName: string;
  villageName: string;
  districtName: string;
  tehsilName: string;
  pinCd?:number;
}
export interface UserAddressList {
  districtCd: number;
  stateCd: number;
  tehsilCd: number;
  villageCd: number;
  pinCd?:number;
}
